
set_property PACKAGE_PIN G9 [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN F9 [get_ports c0_sys_clk_n]

set_property PACKAGE_PIN J10 [get_ports {c0_ddr4_adr[16]}]
set_property PACKAGE_PIN F8 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN D10 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN J8 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN J9 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN E12 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN E8 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN H8 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN D11 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN L8 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN B10 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN L9 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN E10 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN G11 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN A10 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN K8 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN A9 [get_ports {c0_ddr4_adr[0]}]

set_property PACKAGE_PIN K10 [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN D9 [get_ports {c0_ddr4_ba[0]}]

set_property PACKAGE_PIN B9 [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN F12 [get_ports {c0_ddr4_cs_n[0]}]

set_property PACKAGE_PIN E11 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN H11 [get_ports {c0_ddr4_dm_dbi_n[0]}]

set_property PACKAGE_PIN A13 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN D13 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN B12 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN C13 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN C12 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN A12 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN C11 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN B11 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN G12 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN K12 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN K11 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN J13 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN J11 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN H12 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN L12 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN H13 [get_ports {c0_ddr4_dq[0]}]

set_property PACKAGE_PIN F13 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN E13 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN L13 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN K13 [get_ports {c0_ddr4_dqs_c[0]}]

set_property PACKAGE_PIN C8 [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN C9 [get_ports {c0_ddr4_bg[0]}]

set_property PACKAGE_PIN E27 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN D8 [get_ports c0_ddr4_act_n]

set_property PACKAGE_PIN G10 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN F10 [get_ports {c0_ddr4_ck_c[0]}]


set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_n]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[16]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[15]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[14]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[13]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[12]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[11]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[10]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[9]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[8]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[7]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[6]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[5]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[4]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[3]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[2]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_adr[0]}]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_ba[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_ba[0]}]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_cke[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_cs_n[0]}]

set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dm_dbi_n[0]}]

set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[15]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[14]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[13]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[12]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[11]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[10]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[9]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[8]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[0]}]

set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_t[0]}]

set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c0_ddr4_dqs_c[0]}]

set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_odt[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {c0_ddr4_bg[0]}]

set_property IOSTANDARD LVCMOS12 [get_ports c0_ddr4_reset_n]
set_property IOSTANDARD SSTL12_DCI [get_ports c0_ddr4_act_n]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {c0_ddr4_ck_c[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {c0_ddr4_ck_t[0]}]